In [1]:
import pickle
import numpy as np

In [2]:
pipe = pickle.load(open('pipe.pkl', 'rb'))

In [3]:
# Assume user input

test_input2 = np.array([2, 'male', 31.0,  0, 0, 10.5, 'S'], dtype=object).reshape(1, 7)

In [4]:
pipe.predict(test_input2)

C:\Users\Adnan\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\Adnan\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [5]:
test_input2

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [6]:
test_input2[0]

array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object)